### ISSUE TITLE
Question about features in Feature Tracker.

### ISSUE THREAD

**Issue by Gatsby23** [EpicDuckPotato/stereo_vo#3]
![image](https://user-images.githubusercontent.com/18000675/112929309-bd08a580-914a-11eb-897f-e8028d507667.png)
Thanks for your quick replay. I have already test the code on my laptop, but there are some questions about the code. In feature_tracker.cpp, 42 lines, the feature_set and feature_id have already clear() before, but in 45 and 46 lines, it can also visit it, it's weired ? Why it can visit at all？

**Comment by EpicDuckPotato** [comment]
Yep this is a bug. When cpp clears a vector, it isn't guaranteed to actually clear the memory (i.e. it might just reduce the size). This is probably why I was still able to access the vector elements after they'd been cleared. I fixed this in the latest commit.
